name: kms_bpkp_mobile
description: KMS BPKP MOBILE
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  nb_utils: ^6.1.3
  shared_preferences: ^2.2.3
  get: ^4.6.5
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.1
  empty_widget: ^0.0.5
  package_info_plus: ^8.0.0
  cached_network_image: ^3.3.1
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.3.0
  provider: ^6.1.2
  file_picker: ^6.2.1
  flutter_fast_forms: ^17.0.0
  dropdown_search: ^5.0.6
  form_validator: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/json/
